s=('g','e','k','s',)
s.add('f')
print('set after updating:',s)
s.descard('g')
print('\nset afeter updating:',s)
s.remove('e')
print('\nset afte updating:',s)
print('popped elements are',s.pop())
s.pop()
print('\nset fet upaditng :',s)
s.clear()
print('\nset after updating:',s)